### ISSUE TITLE
Mac ctaAnalysis install

### ISSUE THREAD

**Issue by kjrule** [sergiohcdna/ctaAnalysis#5]
Hi,

I am using mac and have installed ctools and gammapy. I cloned the ctaAnalysis repository onto my machine. In my environment set up in the ctools install I am trying to pip install ctaAnalysis and am getting this error:

ERROR: Could not find a version that satisfies the requirement ctaAnalysis (from versions: none)

How can I resolve this?

Thanks,
Kieran

**Comment by sergiohcdna** [comment]
Hi Kieran!

Sure, the error is because pip search ctaAnalysis under PyPi database. At this moment, we hadn't (and probably we won't) submit or publish the package under PyPi. You already clone the package, so you only need to do the following:

```
# change to the directory where you put ctaAnalysis package, for example under home
$ cd ~/ctaAnalysis
# then install the local package with pip
pip install .
```

The last instruction tells pip to use the setup.py script located in the current directory.

Hope this helps.
